In [3]:
import os 
import sqlite3

print("Current folder:\n\n", os.getcwd())
print("DB exists here:\n\n", os.path.exists("Hotel.db"))
print("DB absolute path:\n\n", os.path.abspath("Hotel.db"))

Current folder:

 c:\Users\Favor\Documents\MY_WORKSPACE\02_SCHOLARSHIPS\02_DATA_SCIENCE_TECHCRUSH\mini-projects\capstone
DB exists here:

 True
DB absolute path:

 c:\Users\Favor\Documents\MY_WORKSPACE\02_SCHOLARSHIPS\02_DATA_SCIENCE_TECHCRUSH\mini-projects\capstone\Hotel.db

In [4]:
import pandas as pd

# Use an absolute path 
db_path =  r"C:\Users\Favor\Documents\MY_WORKSPACE\02_SCHOLARSHIPS\02_DATA_SCIENCE_TECHCRUSH\mini-projects\capstone"

# Read the CSV
df = pd.read_csv("hotel_bookings_cleaned.csv")

# Connect to SQLite
conn = sqlite3.connect("hospitality_sqlite3.db")

# Save as a SQL table
df.to_sql("hotel_bookings", conn, if_exists="replace", index=False)

# Verify
result = pd.read_sql_query("SELECT * FROM hotel_bookings LIMIT 5", conn)
result

,Unnamed: 0,booking_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,...,room_nights,revenue,arrival_date,month,month_name,weekday,is_weekend,season,country_full,country_grouped
0,2,3,Resort Hotel,0,7,2015,July,27,1,0,...,1,75.0,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
1,3,4,Resort Hotel,0,13,2015,July,27,1,0,...,1,75.0,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
2,4,5,Resort Hotel,0,14,2015,July,27,1,0,...,2,196.0,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
3,5,6,Resort Hotel,0,14,2015,July,27,1,0,...,2,196.0,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
4,6,7,Resort Hotel,0,0,2015,July,27,1,0,...,2,214.0,2015-07-01,7,July,Wednesday,0,Summer,Portugal,Portugal

In [5]:
directory_files = pd.DataFrame({
    "ID": range(1, len(os.listdir()) + 1),
    "Files":os.listdir(),
})

directory_files

    ID                         Files
0    1                          docs
1    2                    example.db
2    3     G6_Hospitaity_Model.ipynb
3    4     G6_Hospitality_Report.pdf
4    5    G6_Hospitality_Slides.pptx
5    6        G6_Hospitality_SQL.sql
6    7        hospitality_sqlite3.db
7    8                      Hotel.db
8    9    hotel_bookings_cleaned.csv
9   10               hotel_sqlite.db
10  11  queries←sqlite3&duckdb.ipynb
11  12                 sqlite3.ipynb

In [6]:
df_cleaned = pd.read_sql_query("""
SELECT
    arrival_date_month,
    ROUND(SUM(adr * (stays_in_weekend_nights + stays_in_week_nights)),2) AS total_revenue
FROM hotel_bookings
GROUP BY arrival_date_month
ORDER BY total_revenue DESC
""", conn)

print("Season that generates the most revenue:")
df_cleaned

Season that generates the most revenue:

   arrival_date_month  total_revenue
0              August     4825766.72
1                July     4070035.00
2                June     2577766.18
3                 May     2388917.18
4           September     2340387.54
5               April     2093660.62
6             October     1852265.15
7               March     1649445.21
8            February     1143921.28
9            December     1075802.28
10           November     1033481.55
11            January      774506.40

In [7]:
df_cleaned = pd.read_sql_query("""
SELECT *
FROM hotel_bookings
""", conn)

df_cleaned.head(10)

,Unnamed: 0,booking_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,...,room_nights,revenue,arrival_date,month,month_name,weekday,is_weekend,season,country_full,country_grouped
0,2,3,Resort Hotel,0,7,2015,July,27,1,0,...,1,75.00,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
1,3,4,Resort Hotel,0,13,2015,July,27,1,0,...,1,75.00,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
2,4,5,Resort Hotel,0,14,2015,July,27,1,0,...,2,196.00,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
3,5,6,Resort Hotel,0,14,2015,July,27,1,0,...,2,196.00,2015-07-01,7,July,Wednesday,0,Summer,United Kingdom,United Kingdom
4,6,7,Resort Hotel,0,0,2015,July,27,1,0,...,2,214.00,2015-07-01,7,July,Wednesday,0,Summer,Portugal,Portugal
5,7,8,Resort Hotel,0,9,2015,July,27,1,0,...,2,206.00,2015-07-01,7,July,Wednesday,0,Summer,Portugal,Portugal
6,11,9,Resort Hotel,0,35,2015,July,27,1,0,...,4,580.00,2015-07-01,7,July,Wednesday,0,Summer,Portugal,Portugal
7,12,10,Resort Hotel,0,68,2015,July,27,1,0,...,4,388.00,2015-07-01,7,July,Wednesday,0,Summer,United States,United States
8,13,11,Resort Hotel,0,18,2015,July,27,1,0,...,4,619.08,2015-07-01,7,July,Wednesday,0,Summer,Spain,Spain
9,14,12,Resort Hotel,0,37,2015,July,27,1,0,...,4,378.84,2015-07-01,7,July,Wednesday,0,Summer,Portugal,Portugal